Database
fack2/Restaurant- pull request #11
Opened 2019-07-23 14:06 UTC by Nadeen123

2019-07-23 14:07 UTC, sara219 approved these changes

2019-07-23 14:07 UTC, 95Rawan approved these changes

2019-07-24 05:48 UTC, mhmdtshref requested changes
Good job.

Would be better if you create a `cuisines` table and which contains the `id`, `name` and `image_url` to it. And create a one-to-many relation between it and the restaurant table.

2019-07-24 05:48 UTC, mhmdtshref commented on src/database/db_build.sql
> +create table details(
Why do we need this table to be implemented? It's a one-to-one relationship between the restaurant table and its details table. So, you can store all of these data of restaurant in one table called `restaurant`.

2019-07-24 05:48 UTC, mhmdtshref commented on src/database/db_build.sql
> + delivery text not null,
This field type can be `boolean`. Because it contains only 2 possible values, yes or no. So, `true` means `yes` and `false` means `No`.

2019-07-24 05:48 UTC, mhmdtshref commented on src/database/db_build.sql
> +values('02 221 4839','yes','https://www.facebook.com/RozaCrunchy/','/public/image/rosamenu.jpg'),
Notes:
- All facebook links start with `https://www.facebook.com/`. So we don't need to add it to every database facebook links.
- The same issue for the images, all images are in `/public/image/`, so we don't need to add it to all of the images links in DB.

2019-07-24 05:48 UTC, mhmdtshref commented on src/database/db_build.sql
> +DROP TABLE IF EXISTS details CASCADE;
You can DROP multiple tables using one statement:
```sql
DROP TABLE IF EXISTS restaurant, details CASCADE;
```

2019-07-24 05:48 UTC, eadehemingway reviewed
when you have images or other stuff that is not code but needs to be in the repo we tend to keep it in an assets folder to keep things tidy

2019-07-24 07:00 UTC, mhmdtshref requested changes
There's a conflict, merge the master branch and push it up after resolving.

2019-07-24 07:02 UTC, mhmdtshref approved these changes
Sorry, No conflicts anymore, happy to merge it.

2019-07-24 07:02 UTC, merged