half of the design of form and li
fack2/Restaurant- pull request #15
Opened 2019-07-24 13:12 UTC by sara219

2019-07-24 14:04 UTC, mhmdtshref requested changes
Great, I've left some comments, check it and I'll review it again.

2019-07-24 14:04 UTC, mhmdtshref commented on public/style.css
> +    padding: 25px;
Preferred to use percentage `%` for setting `CSS padding`.

2019-07-24 14:04 UTC, mhmdtshref commented on public/style.css
> +#contact h4 {
I cannot see any `h4` elements inside `#contant` form. This can be deleted

2019-07-24 14:04 UTC, mhmdtshref commented on public/style.css
> +fieldset {
fieldset will be removed (view my comment in the HTML file)

2019-07-24 14:04 UTC, mhmdtshref commented on public/index.html
> +            <fieldset>
You don't need to use `fieldset` for each input.
Actually, you don't need to use it at all in this case. Delete it and make sure that you fix the CSS issue after deleting it.

2019-07-24 14:04 UTC, mhmdtshref commented on public/style.css
> +#contact input[type="url"],
The previous 4-lines can be replaced with `#contact input`.

2019-07-24 14:04 UTC, mhmdtshref commented on public/style.css
> +#contact button[type="submit"] {
You don't need to add `[type="submit"]` to the code, try to minimize the code as possible.

2019-07-24 14:04 UTC, mhmdtshref commented on public/style.css
> +/* li {
Remove this comment if you don't need it.

2019-07-24 14:04 UTC, mhmdtshref commented on public/style.css
> +    max-width: 400px;
If you need to add max-width, I think it should be using percentage `%`

2019-07-24 14:07 UTC, mhmdtshref requested changes
Great, I've left some comments, check it and I'll review it again.

2019-07-25 06:01 UTC, Nadeen-Sh approved these changes

2019-07-25 06:05 UTC, merged